name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event.pull_request.draft == false
    
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: actionlint
        run: |
          curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/011a6d15e749bb3f2d771eed9c7aa0e7e3e10ee7/scripts/download-actionlint.bash \
            | bash -s -- 1.7.12 "$RUNNER_TEMP"
          "$RUNNER_TEMP/actionlint" -color
